### ISSUE TITLE
Give the controller permissions to update finalizers on pipelineruns

### ISSUE THREAD

**Issue by gbenhaim** [konflux-ci/tekton-kueue#27]
```yaml
rules:
- apiGroups:
  - tekton.dev
  resources:
  - pipelineruns/finalizers
  verbs:
  - update
```

Without it, when deploying on openshift, the controller throws the following error:

```
 is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: 

...
```
